import { API, graphqlOperation } from 'aws-amplify';
import { Operation } from '../types/operation.types';

/**
 * GraphQL mutation to create a TripOperation
 * Auto-generated by Amplify after running `amplify push`
 */
const createTripOperation = /* GraphQL */ `
  mutation CreateTripOperation($input: CreateTripOperationInput!) {
    createTripOperation(input: $input) {
      id
      tripID
      timestamp
      opId
      userId
      sequenceNumber
      type
      target
      dayNumber
      operationData
      ttl
      createdAt
      updatedAt
    }
  }
`;

/**
 * GraphQL query to list operations by tripID
 * Uses the custom @key(name: "byTripID") GSI from schema
 */
const listOperationsByTrip = /* GraphQL */ `
  query ListOperationsByTrip($tripID: ID!, $limit: Int, $nextToken: String) {
    listOperationsByTrip(tripID: $tripID, limit: $limit, nextToken: $nextToken) {
      items {
        id
        tripID
        timestamp
        opId
        userId
        sequenceNumber
        type
        target
        dayNumber
        operationData
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

/**
 * Save a single operation to DynamoDB via GraphQL
 * @param operation The operation to save
 * @returns Promise<boolean> Success status
 */
export async function saveOperation(operation: Operation): Promise<boolean> {
  if (!operation) {
    console.log('[tripOperationsService] Null operation - skipping');
    return false;
  }

  console.log('[tripOperationsService] Saving operation via GraphQL:', operation.type, operation.opId);
  console.log('[tripOperationsService] 🔑 Operation userId:', operation.userId);

  try {
    // Calculate TTL: current time + 1 hour (in Unix timestamp seconds)
    const ttl = Math.floor(Date.now() / 1000) + (60 * 60); // 1 hour from now

    const input = {
      tripID: operation.tripID,
      timestamp: operation.timestamp,
      opId: operation.opId,
      userId: operation.userId,
      sequenceNumber: operation.sequenceNumber,
      type: operation.type,
      target: operation.target,
      dayNumber: operation.dayNumber,
      operationData: JSON.stringify(operation), // Store full operation as JSON
      ttl: ttl, // DynamoDB will auto-delete after 1 hour
    };

    console.log('[tripOperationsService] 🔑 Sending userId to GraphQL:', input.userId);
    console.log('[tripOperationsService] ⏰ TTL set to:', new Date(ttl * 1000).toISOString(), '(1 hour from now)');

    await API.graphql(graphqlOperation(createTripOperation, { input }));

    console.log('[tripOperationsService] ✅ Operation saved successfully via GraphQL');
    return true;
  } catch (error: any) {
    console.error('[tripOperationsService] ❌ Failed to save operation:', error);
    return false;
  }
}

/**
 * List all operations for a trip via GraphQL
 * @param tripID The trip ID
 * @param limit Maximum number of operations to retrieve (default: 1000)
 * @returns Promise<Operation[]> Array of operations sorted by timestamp
 */
export async function listOperations(
  tripID: string,
  limit: number = 1000
): Promise<Operation[]> {
  try {
    console.log('[tripOperationsService] Listing operations for trip via GraphQL:', tripID);

    const result: any = await API.graphql(
      graphqlOperation(listOperationsByTrip, { tripID, limit })
    );

    const items = result.data?.listOperationsByTrip?.items || [];

    // Parse operationData JSON and sort by timestamp (and sequenceNumber if same timestamp)
    const operations = items
      .map((item: any) => {
        try {
          return JSON.parse(item.operationData) as Operation;
        } catch (error) {
          console.error('[tripOperationsService] Failed to parse operation:', item.opId, error);
          return null;
        }
      })
      .filter((op: Operation | null) => op !== null)
      .sort((a: Operation, b: Operation) => {
        // Primary sort: timestamp
        if (a.timestamp !== b.timestamp) {
          return a.timestamp - b.timestamp;
        }
        // Secondary sort: sequence number
        return a.sequenceNumber - b.sequenceNumber;
      });

    console.log('[tripOperationsService] ✅ Loaded', operations.length, 'operations via GraphQL');

    return operations;
  } catch (error: any) {
    console.error('[tripOperationsService] ❌ Failed to list operations:', error);
    return [];
  }
}

/**
 * Save multiple operations in parallel via GraphQL
 * @param operations Array of operations to save
 * @returns Promise<number> Number of successfully saved operations
 */
export async function saveOperationsBatch(operations: Operation[]): Promise<number> {
  if (!operations || operations.length === 0) {
    return 0;
  }

  console.log('[tripOperationsService] Saving', operations.length, 'operations in batch via GraphQL');

  const results = await Promise.allSettled(
    operations.map((op) => saveOperation(op))
  );

  const succeeded = results.filter(
    (r) => r.status === 'fulfilled' && r.value
  ).length;

  console.log('[tripOperationsService] Saved', succeeded, '/', operations.length, 'operations');

  return succeeded;
}
