import { Colors } from '../constants/Colors';
import { useRouter } from 'expo-router';
import React from 'react';
import { Image, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import './App.css';

import { Amplify } from 'aws-amplify';
import awsExports from '../aws-exports';

import '@aws-amplify/ui-react/styles.css';
Amplify.configure(awsExports);

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';

export default function Login() {
  const router = useRouter();

  return (
    <View>
        <Image source = {require('../assets/images/multiethnic-friends-having-fun-walking-on-city-street---group-1.webp')}
            style={{
                width:'100%',
                height:500
            }}
        />
        <View style = {styles.container}>
           <Text style={{
               fontSize:30,
               fontFamily:'outfit-bold',
               textAlign:'center',
               marginTop:10
           }}>Atelic</Text>
            
           <Text style = {{
                fontFamily:'outfit',
                fontSize:17,
                textAlign:'center',
                color:Colors.GRAY,
                marginTop:20,
           }}>Atelic is an AI platform that helps users easily organize their trip itineraries and optimize their activity routes</Text>
           
           <TouchableOpacity style = {styles.button}
                onPress={()=>router.push('/authorization/sign-in')}
                //onPress={()=>router.push('/create-trip/text_recognition')}
                //onPress={()=>router.push('trip-view/map_directions_test_screen')}
                
           > 
                <Text style = {{color:Colors.WHITE, 
                    textAlign:'center', // on press on event
                    fontFamily:'outfit',
                    fontSize:17
                }}>Login</Text> 
            </TouchableOpacity>
        </View>     
   </View>
 )
}
// why is this not showing?? sign in with google? 

const styles = StyleSheet.create({
   container:{
       backgroundColor:Colors.WHITE,
       marginTop:-20,
       borderTopRightRadius:30,
       borderTopLeftRadius:30,
       padding:15,
       height:'100%',
   },
   button:{
    padding:15,
    backgroundColor:Colors.PRIMARY,
    borderRadius:99,
    marginTop:'25%'
   }
})
//one misspelling can deter the colors. caps vs no caps primary.

